### ISSUE TITLE
[IMPROVEMENT: CODE] Audit `config.matcher` in middleware.ts file for blocking API endpoints

### ISSUE THREAD

**Issue by realChakrawarti** [realChakrawarti/yt-catalog#89]
### Tasks:

- [ ] Make a list of all endpoints, protected and public
- [ ] Classify the endpoints paths in either within `(protected)` and `(public)` folder
- [ ] Research if we could possibly create an OpenAPI specification and render the API references using swagger/scalar
