### ISSUE TITLE
[IMPROVEMENT: FRONT-END] Minor UI/UX tweaks and fixes 

### ISSUE THREAD

**Issue by realChakrawarti** [realChakrawarti/yt-catalog#99]
# Tasks:

## 1. Appbar 
- [ ] #102
- [ ] When opened on mobile devices, and clicked on any sidebar item like "Catalogs" or "Archives", close the sidebar.
- [ ] Move the version from the footer of the application to the Appbar. Add a SidebarFooter for that. 
## 2. Next update catalog banner `src/app/(views)/(public)/c/[catalogId]/next-update.tsx`
- [ ] Show the button outline in white in dark mode, currently its black/dark.
- [ ] Add a margin around the banner so it doesn't take the full width of the viewport.
## 3. Catalog page
- [ ] When description sheet is opened from YouTube card top left `i` icon, sometimes the video title overlaps with the "X" button. Add a top margin to the title.
- [ ] When filter sheet is opened, take up the entire width when opened on mobile devices similar to description modal but the normally should take the existing width.
- [ ] Once the filter sheet is closed, remove focus from the button
- [ ] When channel title is long, it goes past the confinement of the card. Probably use percentage for the channel title so when it overflows, use ellipsis? Refer: ⬇️
  
  ![image](https://github.com/user-attachments/assets/f1d9a2e3-f54b-4b23-b19a-cd5214ccfa73)

## 4. Logout
- [ ] On logging out from header, if user is in unauthenticated routes like `/explore`, `/explore/catalogs`, `explore/watch-later` or inside a individual catalog/archive, it redirects to `/` root. This shouldn't happen. Only when user is in authenticated routes like `/dashboard`, they should be redirected to `/` otherwise should stay put.
